### ISSUE TITLE
Procon OutputReport write error 22.

### ISSUE THREAD

**Issue by nyxrobotics** [unvirus/proconcon#5]
### 概要
表題のエラーが出て実行できませんでした。対処法ご存知でしたらご返信いただけると幸いです。

### 環境
ハードウエア:Raspberry Pi 4B
OS:Ubuntu 20.04.5 LTS
Kernel:5.4.0-1073-raspi
接続方法:Switch -> セルフパワーUSBハブ -> Type-Cポート -> Raspberry Pi
（Raspiは電源入力と通信の両方をType-Cポートで行っています）
load_procon.shが正常起動しているためポートの設定は完了していると思われますが、write権限でエラーが出ているように思われます。

### 実行結果
```bash
$ sudo ./load_procon.sh
$ sudo ./proconcon.out

Procon Converter start.
Keyboard:/dev/input/by-id/usb-CATEX_TECH-event-kbd
Mouse:/dev/input/by-id/usb-SINOWEALTH_Wired_Gaming_Mouse-event-mouse
InputReportThread start.
OutputReportThread start.
KeybordThread start.
MouseThread start.
Procon OutputReport write error 22.
OutputReportThread exit.
KeybordThread exit.
MouseThread exit.
InputReportThread exit.
Procon Converter exit.
```

**Comment by unvirus** [comment]
Procon OutputReport write error 22.
の22がプロコンにwrite()したときのエラーとなっています。
「linux エラーコード」などでググるとエラーコードがわかりますが
22はEINVALで引数が無効と言っています。

ログを見たところ、プロコンを発見できていないようです。
ソースを見直してみましたが
ProconHidrawNameGet()にバグがあるようで、プロコンが見つからなくても処理が進んでしまうようです。
ProconHidrawNameGet()はプロコンのデバイス名を取得する関数です。

    found = 0;　-1で初期化しないと駄目
    dp = readdir(dir);
    while (dp != NULL)

正しい動きとしては以下のようになります。
Procon Converter start.
Keyboard:/dev/input/by-id/usb-Topre_Corporation_Realforce_108-event-kbd
Mouse:/dev/input/by-id/usb-Logitech_G403_Prodigy_Gaming_Mouse_148B38643831-event-mouse
Procon:/dev/hidraw0　　　//プロコンが見つかるとhidrawのデバイス名が表示される
InputReportThread start.
OutputReportThread start.
KeybordThread start.
MouseThread start.

Ubuntu 20.04.5 LTSのhidraw情報のフォルダなどが
Raspbian osと異なっている可能性があります。

**Comment by unvirus** [comment]
Ubuntu 20.04.5 LTS(POE給電）で確認しましたが正常動作しました。
ちなみに、CUIモードで動作検証しています。

**Comment by nyxrobotics** [comment]
ご返信ありがとうございます。理解いたしました。
